server:
  error:
    include-message: always
    include-binding-errors: always

spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: email@gmail.com
    password: blablabla
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
          enable : true
  datasource:
    url: jdbc:postgresql://localhost:5432/registration
    username: sarthak # Replace with your actual DB username
    password: InstagramCloneforsarthak # Replace with your password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
